// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3y07OQoIY3WuSW9bwhHb8ixXh53EFrW4',
    appId: '1:201087922710:web:565819f87cb1587f9efb37',
    messagingSenderId: '201087922710',
    projectId: 'furry-nebula',
    authDomain: 'furry-nebula.firebaseapp.com',
    storageBucket: 'furry-nebula.appspot.com',
    measurementId: 'G-GK9EL88D18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcHN3YiErfVgzZvpS-en1P40T_qHJcfHE',
    appId: '1:201087922710:android:90b5269eb7706ec89efb37',
    messagingSenderId: '201087922710',
    projectId: 'furry-nebula',
    storageBucket: 'furry-nebula.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8FfDvG_EIouzby-9rSL10rcj7-t-bfl0',
    appId: '1:201087922710:ios:45d7cca2dd4948cd9efb37',
    messagingSenderId: '201087922710',
    projectId: 'furry-nebula',
    storageBucket: 'furry-nebula.appspot.com',
    iosClientId: '201087922710-kaijek4hofsf9rtrovv13p29phjoj6pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.furryNebula',
  );
}
