package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	general_errors "github.com/VidroX/furry-nebula/errors/general"
	"github.com/VidroX/furry-nebula/graph/model"
	"github.com/VidroX/furry-nebula/services/translator"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.UserWithToken, error) {
	gCtx := GetGinContext(ctx)
	userService := gCtx.GetServices().UserService

	user, err := userService.Login(email, password)

	if err != nil {
		return nil, FormatError(gCtx.GetLocalizer(), err)
	}

	return user, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, userInfo model.UserRegistrationInput) (*model.UserWithToken, error) {
	gCtx := GetGinContext(ctx)
	userService := gCtx.GetServices().UserService

	user, err := userService.Register(userInfo)

	if err != nil {
		return nil, FormatError(gCtx.GetLocalizer(), err)
	}

	return user, nil
}

// ChangeUserApprovalStatus is the resolver for the changeUserApprovalStatus field.
func (r *mutationResolver) ChangeUserApprovalStatus(ctx context.Context, userID string, isApproved bool) (*model.ResponseMessage, error) {
	gCtx := GetGinContext(ctx)
	userService := gCtx.GetServices().UserService

	err := userService.ChangeUserApprovalStatus(userID, isApproved)

	if err != nil {
		return nil, FormatError(gCtx.GetLocalizer(), err)
	}

	return &model.ResponseMessage{
		Message: translator.WithKey(translator.KeysUserServiceStatusChanged).Translate(gCtx.GetLocalizer()),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	gCtx := GetGinContext(ctx)
	user, err := gCtx.RequireUser()

	if err != nil {
		return nil, FormatError(gCtx.GetLocalizer(), err)
	}

	return user, nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *model.User) (model.Role, error) {
	gCtx := GetGinContext(ctx)
	role := model.Role(obj.RoleName)

	var err error
	if !role.IsValid() {
		err = FormatError(gCtx.GetLocalizer(), &general_errors.ErrInternal)
	}

	return role, err
}

// IsApproved is the resolver for the isApproved field.
func (r *userResolver) IsApproved(ctx context.Context, obj *model.User) (bool, error) {
	gCtx := GetGinContext(ctx)
	userRepo := gCtx.GetRepositories().UserRepository

	isApproved, err := userRepo.IsUserApproved(obj.ID)

	if err != nil {
		return false, FormatError(gCtx.GetLocalizer(), &general_errors.ErrInternal)
	}

	return isApproved, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
