version: "3.8"
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT_TYPE=release
      - GIN_MODE=release
      - PORT=80
    env_file:
      - ./.env
    ports:
      - "80:80"
    depends_on:
      - postgresql
    links:
      - postgresql

  postgresql:
    image: bitnami/postgresql:15.3.0
    restart: always
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data_container:/data/database

volumes:
  postgresql_data_container: