include: package:lint/strict.yaml

linter:
  rules:
    sort_pub_dependencies: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    unused_element: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**.gen.dart'
    - '**.gql.dart'
    - '**.gql.g.dart'
