targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: furry_nebula|lib/graphql/schema.graphql
          type_overrides:
            Int64:
              name: int
            Time:
              name: DateTime
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: furry_nebula|lib/graphql/schema.graphql