name: furry_nebula
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^7.4.0
  provider: ^6.0.5
  get_it: ^7.6.0
  gql_http_link: ^1.0.1
  ferry: ^0.14.2+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  dio: ^5.2.1+1
  flutter_dotenv: ^5.1.0
  flutter_i18n: ^0.33.0
  flutter_svg: ^2.0.7
  gql_dio_link: ^1.0.1
  gql_link: ^1.0.0
  gql_error_link: ^1.0.0
  gql_dedupe_link: ^2.0.4-alpha+1686240656097
  gql_exec: ^1.0.1-alpha+1686240655996
  gql_transform_link: ^1.0.0
  shared_preferences: ^2.1.2
  intl: ^0.18.0
  built_value: ^8.6.1
  collection: ^1.17.1
  jwt_decoder: ^2.0.1
  font_awesome_flutter: ^10.4.0
  http: ^0.13.6
  shimmer: ^3.0.0
  path_provider: ^2.0.15
  image_picker: ^1.0.0
  mime: ^1.0.4
  http_parser: ^4.0.2
  fast_cached_network_image: ^1.2.0
  transparent_image: ^2.0.1
  animations: ^2.0.7
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  ferry_generator: ^0.8.1
  freezed: ^2.3.5
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  lint: ^2.1.2
  flutter_gen_runner: ^5.3.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/svg/
