FROM golang:1.20.4-bullseye

ENV APP_NAME furry-nebula
ENV APP_HOME /app/${APP_NAME}

ENV GO111MODULE=on
ENV CGO_ENABLED=0

WORKDIR "$APP_HOME"

COPY go.mod go.sum ./

RUN go get github.com/githubnemo/CompileDaemon
RUN go install -v github.com/githubnemo/CompileDaemon

RUN go mod tidy

EXPOSE ${PORT}

ENTRYPOINT CompileDaemon -polling -build="go build -o tmp/app" -command="tmp/app"