name: Analyze and build APK (DEV)

on:
  push:
    branches: ["development"]
  workflow_dispatch:

env:
  WORKING_DIRECTORY: "./app"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      
      - run: flutter pub get

      - run: flutter analyze .

  buildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: development
    needs: [ test ]
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v3

      - name: Upload Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> android/key.properties

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      
      - run: flutter pub get

      - run: flutter build apk --release --dart-define=API_ENV=development --dart-define=API_ENDPOINT=${{ secrets.API_ENDPOINT }}

      - uses: actions/upload-artifact@v3
        with:
          name: furry-nebula-dev
          path: build/app/outputs/apk/release/app-release.apk
